config/routes.rb
Rails.application.routes.draw do
  get :dashboard,  controller: :dashboard, action: :index
  get :reports,  controller: :reports, action: :index

  resources :instances do
    resources :readings, only: [:index, :show], controller: 'instances/readings'
  end

  namespace :api, defaults: { format: :json } do
    resources :readings, only: [:create]
  end

  root 'dashboard#index'
end

app/models/instance.rb
class Instance
  include Mongoid::Document
  include Mongoid::Timestamps

  field :label, type: String
  field :ip, type: String

  has_many :readings

  validates :ip, presence: true
  validates :ip, uniqueness: true, allow_nil: true

  validate :valid_ip

  private

  def valid_ip
    IPAddress.parse(self.ip)
  rescue ArgumentError
    self.errors.add(:ip, 'is invalid')
  end

end

app/models/reading.rb
class Reading
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :instance
  embeds_one :data, class_name: 'ReadingData'

  validates! :instance, presence: true

  validates :data, presence: true

  def self.from_last_hours(hours = 12)
    self.where(:created_at.gte => (Time.now - hours.hours))
  end

  def as_json(*args)
    data = super

    data['created_at'] = self.created_at.utc.iso8601
    data['updated_at'] = self.updated_at.utc.iso8601

    data
  end

end

app/models/reading_data.rb
class ReadingData
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :cpu_usage, type: Float
  field :disk_usage, type: Float

  embedded_in :reading

end

app/controllers/api/readings_controller.rb
class Api::ReadingsController < ApiController

  before_action :set_instance, only: [:create]

  # POST /api/readings
  def create
    instance = Reading.create(reading_params)

    if instance.persisted?
      render json: { messages: ['Reading stored'], actions: [] }
    else
      render json: { messages: instance.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def set_instance
    @instance ||= Instance.find_by!(ip: request.remote_ip)
  rescue Mongoid::Errors::DocumentNotFound
    render json: { messages: ['Instance not registered'] }, status: :not_found
  end

  def reading_params
    params.require(:reading).permit!.merge(instance: @instance)
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  protect_from_forgery with: :null_session

  rescue_from ActionController::ParameterMissing do |exception|
    render json: { messages: ["Parameter #{exception.param} is required"] },
           status: :unprocessable_entity
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @instances = Instance.all
  end

end

app/controllers/instances/readings_controller.rb
class Instances::ReadingsController < ApplicationController

  before_action :set_instance
  before_action :set_reading, only: [:show]

  # GET /instances/:instance_id/readings
  def index
    readings = @instance.readings.from_last_hours(2)

    render json: readings.to_json
  end

  # GET /instances/:instance_id/readings/:id
  def show
  end

  private

  def set_instance
    @instance ||= Instance.find(params[:instance_id])
  rescue Mongoid::Errors::DocumentNotFound
    render json: { messages: ['Instance not found'] }, status: :not_found
  end

  def set_reading
    @reading ||= @instance.readings.find(params[:id])
  rescue Mongoid::Errors::DocumentNotFound
    render json: { messages: ['Reading not found'] }, status: :not_found
  end

end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController

  before_action :set_instance, only: [:show, :edit, :update, :destroy]

  # GET /instances
  def index
    @instances = Instance.all
  end

  # GET /instances/1
  def show
  end

  # GET /instances/new
  def new
    @instance = Instance.new
  end

  # GET /instances/1/edit
  def edit
  end

  # POST /instances
  def create
    @instance = Instance.new(instance_params)

    if @instance.save
      redirect_to @instance, notice: 'Instance was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /instances/1
  def update
    if @instance.update(instance_params)
      redirect_to @instance, notice: 'Instance was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /instances/1
  def destroy
    @instance.destroy

    redirect_to instances_url, notice: 'Instance was successfully destroyed.'
  end

  private

  def set_instance
    @instance = Instance.find(params[:id])
  rescue Mongoid::Errors::DocumentNotFound
    redirect_to instances_path, alert: 'Instance not found.'
  end

  def instance_params
    params.require(:instance).permit(:ip, :label)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @cpu_usage_rank = cpu_usage_rank
    @low_disk_space = low_disk_usage
  end

  private

  def cpu_usage_rank
    Instance.all.map do |instance|
      reading = instance.readings.last

      next unless reading

      cpu_usage = reading.data.cpu_usage

      next unless cpu_usage

      [instance, cpu_usage]
    end.compact
       .sort_by { |_, cpu_usage| cpu_usage }
       .reverse
  end

  def low_disk_usage
    Instance.all.map do |instance|
      reading = instance.readings.last

      next unless reading

      disk_usage = reading.data.disk_usage

      next unless disk_usage

      [instance, disk_usage]
    end.compact
       .select { |_, disk_usage| disk_usage > 90 }
       .sort_by { |_, disk_usage| disk_usage }
  end

end

app/helpers/instances_helper.rb
module InstancesHelper

  def instance_title(instance)
    if instance.label.present?
      "#{instance.label} [#{instance.ip}]"
    else
      "#{instance.ip}"
    end
  end

end

app/views/dashboard/index.html.slim
- @instances.each do |instance|
  h1= link_to instance_title(instance), instance_path(instance)
  = render 'instances/charts', instance: instance

app/views/instances/_charts.html.slim
- show_table = local_assigns.fetch(:show_table, false)
.row.instance-charts data={ instance_id: instance.id, readings_path: instance_readings_path(instance) }
  div id="cpu-usage-chart-#{instance.id}"
  div id="disk-usage-chart-#{instance.id}"
  div id="scan-chart-#{instance.id}"

  - if show_table
    table.table.table-striped id="data-table-#{instance.id}"
      thead
        tr
          th Id
          th Date
          th CPU Usage
          th Disk Usage

app/views/instances/_form.html.slim
= form_for @instance, html: { class: 'form form-horizontal instance' } do |f|
  .form-group
    = f.label :label, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :label, class: 'form-control'
    = f.error_span(:label)

  .form-group
    = f.label :ip, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :ip, class: 'form-control'
    = f.error_span(:ip)

  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, class: 'btn btn-primary'
      '
      = link_to t('.cancel', default: t('helpers.links.cancel')), instances_path, class: 'btn'

app/views/instances/edit.html.slim
.page-header
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: 'Instance'

= render partial: 'form'

app/views/instances/index.html.slim
- model_class = Instance
.page-header
  h1
    =t '.title', default: 'Instances'
    = link_to t('.new', default: t("helpers.links.new")), new_instance_path, class: 'btn btn-primary pull-right'

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:ip)
      th= model_class.human_attribute_name(:label)
      th=t '.actions', default: t('helpers.actions')

  tbody
    - @instances.each do |instance|
      tr
        td= link_to instance.ip, instance_path(instance)
        td= instance.label
        td
          = link_to t('.edit', default: t("helpers.links.edit")), edit_instance_path(instance), class: 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', default: t("helpers.links.destroy")), instance_path(instance),
                    method: :delete,
                    data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                    class: 'btn btn-xs btn-danger'

app/views/instances/new.html.slim
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: 'Instance'

= render partial: 'form'

app/views/instances/readings/show.html.slim
.page-header
  h1 Reading

p
  strong CPU Usage:
  br
  = number_to_human(@reading.data.try(:cpu_usage))

p
  strong Disk Usage:
  br
  = number_to_human(@reading.data.try(:disk_usage))

table.table.table-striped
  thead
    tr
      th Process
      th CPU Usage

  tbody
    - (@reading.data.try(:process_list) || {}).each do |process, cpu_usage|
      tr
        td= process
        td= cpu_usage

app/views/instances/show.html.slim
.page-header
  h1
    = instance_title(@instance)

    .pull-right
      = link_to t('.back', default: t("helpers.links.back")), instances_path, class: 'btn btn-default'
      '
      = link_to t('.edit', default: t("helpers.links.edit")), edit_instance_path(@instance), class: 'btn btn-default'
      '
      = link_to t('.destroy', default: t("helpers.links.destroy")), instance_path(@instance),
                method: :delete,
                data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                class: 'btn btn-danger'

p
  strong= Instance.human_attribute_name(:ip) + ':'
  br
  = @instance.ip

p
  strong= Instance.human_attribute_name(:label) + ':'
  br
  = @instance.label

.row
  .col-lg-12= render 'charts', instance: @instance, show_table: true

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title= content_for?(:title) ? yield(:title) : 'WardWeb'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: :all
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application'
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js'


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-responsive-collapse'
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href=root_path WardWeb
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to 'Dashboard', dashboard_path
            li= link_to 'Instances', instances_path
            li= link_to 'Reports', reports_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

    footer.navbar.navbar-default.navbar-fixed-bottom
      .container.text-right
        p.copyright &copy; Ward 2016

app/views/reports/index.html.slim
.panel.panel-default
  .panel-heading CPU Usage

  table.table.table-striped
    thead
      tr
        th Instance
        th CPU Usage

    tbody
      - @cpu_usage_rank.each do |instance, cpu_usage|
        tr
          td= link_to instance_title(instance), instance_path(instance)
          td= number_to_human(cpu_usage)

.panel.panel-default
  .panel-heading Low disk space

  table.table.table-striped
    thead
      tr
        th Instance
        th Disk Usage

    tbody
      - @low_disk_space.each do |instance, disk_space|
        tr
          td= link_to instance_title(instance), instance_path(instance)
          td= number_to_human(disk_space)